### ISSUE TITLE
Not Authorized issue

### ISSUE THREAD

**Issue by Eyalf** [LiamPa/betfairlightweight#1]
This is not actually an issue, But there is no way to contact people on github. I am having issues with my app key not being authorized, Do you happen to know if this has to be a live key, And if it has to be specially activated by betfair?

Thanks,
Eyal.

**Comment by LiamPa** [comment]
It may be something to do with this:

   http://forum.bdp.betfair.com/showthread.php?t=3174

However send an email to Neil, bdp@betfair.com

**Comment by Eyalf** [comment]
Thanks!
