### ISSUE TITLE
No queue passed to StreamListener.

### ISSUE THREAD

**Issue by minimumnz** [LiamPa/betfairlightweight#2]
I was getting this error:
    self.output_queue.put(output_market_book)
AttributeError: 'NoneType' object has no attribute 'put'

To fix this in apiclient.py I added:

import queue
output_queue = queue.Queue()
and passed this to StreamListener in create_stream()

**Comment by LiamPa** [comment]
Yeh this is a bug if you don't pass a listener when using create_stream(), will fix tonight. 

This is how I have been testing it:

`trading.login()

output_queue = queue.Queue()

listener = betfairlightweight.StreamListener(output_queue)
betfair_socket = trading.create_stream(2, listener=listener, description='Test Market Socket')
betfair_socket.start(True)
betfair_socket.authenticate()`
